[package]
name = "k8s-openapi-ext"
version = "0.27.3"
edition = "2021"
rust-version = "1.88.0"
description = "Collection of fluent builder traits for Kubernetes objects"
repository = "https://github.com/rkubectl/k8s-openapi-ext-rs"
license = "Apache-2.0"
readme = "README.md"


[dependencies]
base64 = "0.22"
jiff = { version = "0.2", features = ["std"] }
k8s-openapi = { version = "0.27", features = [] }
time = { version = "0.3", optional = true }


[dev-dependencies]
serde_json = "1.0"


[dev-dependencies.k8s-openapi]
version = "0.27"
features = ["latest"]


[features]
pedantic = []
time = ["dep:time"]


[package.metadata.docs.rs]
features = ["k8s-openapi/latest", "time"]
